### ISSUE TITLE
Game's crashing

### ISSUE THREAD

**Issue by 1xerr** [LucilleKarma/WrathOfTheGodsPublic#46]
Everytime i load into my world with wrath of gods enabled it causes a main engine crash
Here's logs:
[21:07:06.162] [Main Thread/FATAL] [tML]: Main engine crash

Newtonsoft.Json.JsonSerializationException: Error getting value from 'ScreenShakeIntensity' on 'NoxusBoss.Core.Configuration.NoxusBossConfig'.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NoxusBoss.Common.Utilities.Utilities.GetFromCalamityConfig[T](String propertyName, T defaultValue) in NoxusBoss\Common\Utilities\ConfigUtilities.cs:line 20
   at NoxusBoss.Core.Configuration.NoxusBossConfig.get_ScreenShakeIntensity() in NoxusBossConfig.cs:line 50
   at lambda_method1085(Closure, Object)
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   at Terraria.ModLoader.Config.ConfigManager.GeneratePopulatedClone(ModConfig original) in tModLoader\Terraria\ModLoader\Config\ConfigManager.cs:line 409
   at Terraria.ModLoader.Config.ConfigManager.AnyModNeedsReloadCheckOnly(List`1& modsWithChangedConfigs) in tModLoader\Terraria\ModLoader\Config\ConfigManager.cs:line 277
   at Terraria.Main.PrepareLoadedModsAndConfigsForSingleplayer() in tModLoader\Terraria\Main.TML.cs:line 640
   at DMD<System.Void Terraria.Main:DrawMenu(Microsoft.Xna.Framework.GameTime)>(Main this, GameTime gameTime)
   at NoxusBoss.Content.CustomWorldSeeds.NoxusWorldManager.DrawNoxusSkyDuringWorldGen(orig_DrawMenu orig, Main self, GameTime gameTime)
   at Hook<System.Void NoxusBoss.Content.CustomWorldSeeds.NoxusWorldManager::DrawNoxusSkyDuringWorldGen(Terraria.On_Main+orig_DrawMenu,Terraria.Main,Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at NoxusBoss.Core.Fixes.EternalGardenIntroBackgroundFix.DrawWhite(orig_DrawMenu orig, Main self, GameTime gameTime)
   at Hook<System.Void NoxusBoss.Core.Fixes.EternalGardenIntroBackgroundFix::DrawWhite(Terraria.On_Main+orig_DrawMenu,Terraria.Main,Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at Hook<System.Void NoxusBoss.Core.Graphics.SpecificEffectManagers.NamelessDeityTipsOverrideSystem::ChangeStatusText(Terraria.On_Main+orig_DrawMenu,Terraria.Main,Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at SyncProxy<System.Void Terraria.Main:DrawMenu(Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at DMD<System.Void Terraria.Main:DoDraw(Microsoft.Xna.Framework.GameTime)>(Main this, GameTime gameTime)
   at SyncProxy<System.Void Terraria.Main:DoDraw(Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at Terraria.Main.Draw_Inner(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.RunGame()

**Comment by 1xerr** [comment]
Maybe. But it doesn't get any better.

**Comment by Jebus554** [comment]
You think this will be fixed soon? By tomorrow or 2 days tops.

**Comment by DominicKarma** [comment]
Logs contain anything?

**Comment by 1xerr** [comment]
Umm, everything is working again

**Comment by 1xerr** [comment]
Although I didn't change anything

**Comment by Jebus554** [comment]
Weird.

**Comment by Jebus554** [comment]
nvm still not working for me

**Comment by Jebus554** [comment]
These are my logs 
![Screenshot 2024-05-10 142158](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/169490874/109d894e-181a-48b1-ac34-11c44bae6d6f)

**Comment by zApache** [comment]
just got the same error, any solution?

**Comment by Jebus554** [comment]
I haven't found one, I even tried opening the config and changing the "ScreenShakeIntensity" but it won't work, just crashes and gives me that.

**Comment by Jebus554** [comment]
Maybe if we find a way to change screen shake intensity in the config without it crashing, then it might work.

**Comment by SirYukie** [comment]
you can change the screen shake intensity from the Luminance mod, but it doesnt do anything

**Comment by Jebus554** [comment]
I can give it a shot, doesn't WOTG  work with Luminance?

**Comment by Jebus554** [comment]
It didnt work.

**Comment by RealVehement** [comment]
Pretty sure  the issue is cause the bountiful harvest update dropped, other than that I have no clue why its crashing.

**Comment by Jebus554** [comment]
So the update was today and just messed something up in the mod?

**Comment by RealVehement** [comment]
yup thats what im thinkin, ill test it out rn but im quite sure WOTG is the only one out of the several mods
- Infernum
- Catalyst
- Hunt of the old God 
That im using in my run.

if anything helps this is from the Calamity team,

[https://vxtwitter.com/CalamityModTeam/status/1788992889671897530]

**Comment by RealVehement** [comment]
I can confirm, all of the mods work now.

**Comment by Jebus554** [comment]
So the team is still fixing the problem?

**Comment by Jebus554** [comment]
WAIT, are you saying it's the Calamity mod that is causing some problems to the game? And other mods too?
